# Generated by Django 5.2 on 2025-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_remove_question_has_text_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
