# Generated by Django 5.2 on 2025-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_alter_test_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('variants', 'Вариационный вопрос'), ('text', 'Текстовый ответ')], default='variants', max_length=10),
        ),
    ]
