# Generated by Django 5.2 on 2025-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Вариационный вопрос'), ('text', 'Текстовый ответ')], default='multiple', max_length=10),
        ),
    ]
