# Generated by Django 5.2 on 2025-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_test_max_attempts_alter_test_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, help_text='Время на прохождение теста в минутах (0 - без ограничения)'),
        ),
    ]
