# Generated by Django 5.2 on 2025-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Проходной балл в процентах'),
        ),
    ]
