# Generated by Django 5.2 on 2025-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0012_fix_testresult_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', help_text='Уровень сложности теста', max_length=10),
        ),
    ]
