# Generated by Django 5.2 on 2025-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0013_test_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_abbreviations',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь аббревиатур в формате JSON'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_synonyms',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь синонимов в формате JSON'),
        ),
        migrations.AddField(
            model_name='question',
            name='similarity_threshold',
            field=models.FloatField(default=0.8, help_text='Порог схожести для текстовых ответов (0.0 - 1.0)'),
        ),
    ]
